framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/

        importmap_polyfill: false  # disable ES module shim (disable pollyfill for older browsers)
