nelmio_api_doc:
    documentation:
        info:
            title: API Fútbol
            description: API Fútbol, gestiona competiciones, equipos y jugadores
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            schemas:
                Mensaje:
                    type: object
                    properties:
                        msg:
                            type: string
                            example: "Contenido del mensaje"
                EquipoPlantilla:
                    type: object
                    properties:
                        id:
                            type: integer
                        nombre:
                            type: string
                        pais:
                            type: string
                        plantilla:
                            type: integer
        security:
            - Bearer: [ ]

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/(doc|autenticacion)$) # Accepts routes under /api except /api/doc and /api/autenticacion

    use_validation_groups: true