version: '3'

services:
  nginx:
    container_name: api_nginx
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  enviroment:
    container_name: api_enviroment
    build:
      context: ./docker
    volumes:
      - ./:/var/www